// Phone normalization utility
// Remove all non-digits, then if length==10 and starts with "1", prefix "0"
export function normalizePhone(phone: string): string {
  if (!phone) return '';
  
  // Remove all non-digits
  let digits = phone.replace(/\D/g, '');
  
  // If length==10 and starts with "1" (e.g. 1012345678), prefix "0"
  if (digits.length === 10 && digits.startsWith('1')) {
    digits = '0' + digits;
  }
  
  return digits;
}

// Generate unique student_code from normalized student_phone
// Returns { code, isAutoGenerated } or { code: null, error: string }
export async function generateStudentCode(
  studentPhone: string,
  existingCodes: Set<string>
): Promise<{ code: string | null; isAutoGenerated: boolean; error?: string }> {
  const normalized = normalizePhone(studentPhone);
  
  // Must have at least 4 digits
  if (normalized.length < 4) {
    return { 
      code: null, 
      isAutoGenerated: false, 
      error: '학생번호 생성 불가: 학생전화 없음/짧음' 
    };
  }
  
  // Get last 4 digits
  const last4 = normalized.slice(-4);
  let candidateCode = last4;
  let suffix = 2;
  
  // Find unique code
  while (existingCodes.has(candidateCode)) {
    candidateCode = `${last4}-${suffix}`;
    suffix++;
    
    // Safety limit
    if (suffix > 100) {
      return { 
        code: null, 
        isAutoGenerated: false, 
        error: '학생번호 생성 실패: 중복 과다' 
      };
    }
  }
  
  return { code: candidateCode, isAutoGenerated: true };
}
